name: CI

on:
  schedule:
    - cron: "*/30 * * * *" # 每30分钟自动执行一次
  workflow_dispatch: # 可以手动执行

jobs:
  CheckScores:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set Beijing Time
        run: export BEIJING_TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')"
      
      - name: Print Beijing Time
        run: echo "Beijing Time is $BEIJING_TIME"
      
  BackupMain:
    runs-on: ubuntu-latest
    needs: CheckScores
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Beijing Time in BackupMain
        run: echo "BackupMain Beijing Time is $BEIJING_TIME"
