name: Test

on:
  workflow_dispatch:

jobs:
  job1:
    name: job1

    runs-on: ubuntu-latest

    outputs:
      BEIJING_TIME: ${{ steps.get_current_time.outputs.BEIJING_TIME }}

    steps:
      - name: get current time
        id: get_current_time
        run: |
          export BEIJING_TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')"
          echo "BEIJING_TIME=$BEIJING_TIME" >> $GITHUB_OUTPUT
          echo "${BEIJING_TIME}"


  job2:
    name: job2

    needs: job1

    runs-on: ubuntu-latest

    steps:
      - name: run main
        run: |
          echo "${{ needs.job1.outputs.BEIJING_TIME }}"
