name: My Workflow

on:
  schedule:
    - cron: "*/30 * * * *" # 每30分钟自动执行一次
  workflow_dispatch: # 可以手动执行

env:
  BEIJING_TIME: ${{ steps.set_beijing_time.outputs.beijing_time }}

jobs:
  CheckScores:
    runs-on: ubuntu-latest
    steps:
      - name: Set Beijing Time
        id: set_beijing_time
        run: echo "BEIJING_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')" >> $GITHUB_ENV

      - name: Print Beijing Time
        run: echo "Beijing Time is $BEIJING_TIME"

  BackupMain:
    runs-on: ubuntu-latest
    steps:
      - name: Print Beijing Time
        run: echo "Beijing Time is $BEIJING_TIME"
