name: Test

on:
  schedule:
  workflow_dispatch: # 可以手动执行

  # 检查成绩
  job1:
    name: job1

    # 在最新版的Ubuntu系统上运行
    runs-on: ubuntu-latest

    - name: Run main
        export BEIJING_TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')"
