name: Test

on:
  workflow_dispatch: # 可以手动执行

# 检查成绩
jobs:
  job1:
    name: job1

    # 在最新版的Ubuntu系统上运行
    runs-on: ubuntu-latest

    outputs:
      BEIJING_TIME: ${{ steps.get_current_time.outputs.BEIJING_TIME }}

    steps:
      - name: get current time
        id: get_current_time
        run: |
          export BEIJING_TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')"
          echo "BEIJING_TIME=$BEIJING_TIME" >> $GITHUB_OUTPUT

      - name: run main
        run: |
          echo "${BEIJING_TIME}"
